---
abstract: 'session data store plugin for Mojolicious'
author:
  - 'hayajo <hayajo@cpan.org>'
build_requires:
  Plack::Middleware::Session: 0
  Test::More: 0.88
configure_requires:
  Module::Build::Tiny: 0.019
dynamic_config: 0
generated_by: 'Dist::Milla version v1.0.2, Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Mojolicious-Plugin-SessionStore
no_index:
  directory:
    - t
    - xt
    - inc
    - share
    - eg
    - examples
requires:
  Digest::SHA1: 0
  Mojolicious: 0
  perl: 5.010001
resources:
  bugtracker: https://github.com/hayajo/Mojolicious-Plugin-SessionStore/issues
  homepage: https://github.com/hayajo/Mojolicious-Plugin-SessionStore
  repository: https://github.com/hayajo/Mojolicious-Plugin-SessionStore.git
version: 0.04
